### ISSUE TITLE
Running the Pipeline at scale

### ISSUE THREAD

**Issue by zar1** [dssg/UPSG#33]
Currently, all pipeline stages are run in serial on a single-process. We want to utilize a tool that lets us schedule Stages simultaneously, across cores, across computers, etc. Candidates are Luigi (https://github.com/spotify/luigi) and Drake (https://github.com/Factual/drake).

**Comment by zar1** [comment]
Another candidate is Apache Spark (https://spark.apache.org/).

**Comment by zar1** [comment]
In principal, we can support all the backends. Which one we implement first should be determined by a few factors:
1. It should be as easy as possible to integrate the backend with what we have written already.
2. A fundamental feature of UPSG is that Stages can be written in different languages and run in different processes. Currently, we assume everything is running in serial in memory. Our backend should ideally necessitate that UPSG actually fulfills its promise of working across processes, or at least encourage that sort design.

**Comment by zar1** [comment]
Running on a cluster might necessitate using HDFS instead of local FS.

**Comment by hunterowens** [comment]
Another (vendor specific) option is to use S3 rather than HDFS.

**Comment by zar1** [comment]
True. Do you think S3 would have an advantage over HDFS for UPSG?

**Comment by hunterowens** [comment]
Probably in ease of implementation, as it doesn't require having a running
HDFS filesystem. If you are running on the Amazon Cloud, S3 is often
considered best practice for Elastic Map Reduce usage, as Amazon does a ton
of behind the scenes optimization.

**Comment by mdagost** [comment]
s3 is super simple, and you can process data in s3 from both Spark clusters
booted on ec2 (using the script that comes with Spark) and with EMR
(Amazon's hadoop distro)...

**Comment by zar1** [comment]
We ended up using Luigi as of ccddd014196be9784b36a105682542a803b262c8. We may add something else later.
