### ISSUE TITLE
timezone handling in TestTransform.test_sql

### ISSUE THREAD

**Issue by zar1** [dssg/UPSG#45]
The test expects to run on a computer with a system clock at central time, so the test will fail in any other timezone.

**Comment by zar1** [comment]
This is because Numpy datetime64 does something unexpected and 
1. Assumes that an unspecified time is in UTC
2. Converts to the local time
(https://github.com/numpy/numpy/issues/3290)
SInce numpy is broken, we're going to either have to not use Numpy or find a workaround. For now, we will prefer the latter.

**Comment by johnsanterre** [comment]
http://stackoverflow.com/questions/25134639/how-to-force-python-print-numpy-datetime64-with-specified-timezone

print dt.item()

prints in UTC time...

**Comment by zar1** [comment]
"Fixed" by changing the test in 8cd8542651
