### ISSUE TITLE
cross-validate by time/space.

### ISSUE THREAD

**Issue by zar1** [dssg/UPSG#83]
Probably the best thing to do is subclass sklearn.cross_validation._PartitionIterator (I know. It's an internal API. It's not the best, but sklearn isn't considerate enough to give us an external equivalent.)

**Comment by zar1** [comment]
Done for time in 22fc5c7888dcdb533bff41878fea1d1bddae65db. Still needs a space equivalent.

**Comment by kennyjoseph** [comment]
Nice, cool!

**Comment by zar1** [comment]
Thanks kennyjoseph.

**Comment by zar1** [comment]
Finished forever as of 9088c3fa7f7590302a7bb9d8d269112acd8d639a! Argh! That took so many commits to figure out!
